/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.eurekaappcs.view;

import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRMapCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import pe.egcc.eurekaappcs.controller.CuentaController;
import pe.egcc.eurekaappcs.util.Dialogo;
import util.ReportViewInternal;

/**
 *
 * @author Gustavo Coronel
 */
public class RepoMovimientosView extends javax.swing.JInternalFrame {

  /**
   * Creates new form RepoMovimientosView
   */
  public RepoMovimientosView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelReporte = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtCuenta = new javax.swing.JTextField();
    btnConsultar = new javax.swing.JButton();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("REPORTE DE MOVIMIENTOS");

    javax.swing.GroupLayout panelReporteLayout = new javax.swing.GroupLayout(panelReporte);
    panelReporte.setLayout(panelReporteLayout);
    panelReporteLayout.setHorizontalGroup(
      panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelReporteLayout.setVerticalGroup(
      panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 270, Short.MAX_VALUE)
    );

    jLabel1.setText("Cuenta:");

    btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaappcs/img/buscar.gif"))); // NOI18N
    btnConsultar.setText("Consultar");
    btnConsultar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsultarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnConsultar)
        .addContainerGap(470, Short.MAX_VALUE))
      .addComponent(panelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    try {
      // Dato
      CuentaController control = new CuentaController();
      List<Map<String, ?>> lista = control.getMovimientos(txtCuenta.getText());
      JRMapCollectionDataSource data = new JRMapCollectionDataSource(lista);
      // Cargar el logo
      String fileLogo = "/pe/egcc/eurekaappcs/img/logo.gif";
      InputStream isLogo = Class.class.getResourceAsStream(fileLogo);
      Map<String, Object> pars = new HashMap<>();
      pars.put("LOGO", fileLogo);
      // Creando el archiv JasperPrint
      String fileRepo = "/pe/egcc/eurekaappcs/report/repoMovimientos.jasper";
      InputStream isRepo = Class.class.getResourceAsStream(fileRepo);
      JasperReport jrRepo = (JasperReport) JRLoader.loadObject(isRepo);
      JasperPrint jpRepo = JasperFillManager.fillReport(jrRepo, pars, data);
      // Creando la vista con el reporte
      ReportViewInternal view = new ReportViewInternal("");
      view.setTitle("MOVIMIENTOS DE LA CUENTA " + txtCuenta.getText());
      view.setReporte(jpRepo);
      // Cargar la vista en el panel
      panelReporte.removeAll();
      panelReporte.add(view);
      view.setVisible(true);
      view.setMaximum(true);
      view.setMaximizable(false);
      view.setIconifiable(false);
    } catch (Exception e) {
      e.printStackTrace();
      Dialogo.error(rootPane, e.getMessage());
    }
  }//GEN-LAST:event_btnConsultarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnConsultar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel panelReporte;
  private javax.swing.JTextField txtCuenta;
  // End of variables declaration//GEN-END:variables
}
